# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from finalpro/messagetomotor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class messagetomotor(genpy.Message):
  _md5sum = "ed4140bdc09bbb6c72fbfc9d889eae02"
  _type = "finalpro/messagetomotor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 centx
int16 centy
int16 sudut
int16 kec_x
int16 kec_y
int16 kec_sudut

"""
  __slots__ = ['centx','centy','sudut','kec_x','kec_y','kec_sudut']
  _slot_types = ['int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       centx,centy,sudut,kec_x,kec_y,kec_sudut

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(messagetomotor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.centx is None:
        self.centx = 0
      if self.centy is None:
        self.centy = 0
      if self.sudut is None:
        self.sudut = 0
      if self.kec_x is None:
        self.kec_x = 0
      if self.kec_y is None:
        self.kec_y = 0
      if self.kec_sudut is None:
        self.kec_sudut = 0
    else:
      self.centx = 0
      self.centy = 0
      self.sudut = 0
      self.kec_x = 0
      self.kec_y = 0
      self.kec_sudut = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.centx, _x.centy, _x.sudut, _x.kec_x, _x.kec_y, _x.kec_sudut))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.centx, _x.centy, _x.sudut, _x.kec_x, _x.kec_y, _x.kec_sudut,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.centx, _x.centy, _x.sudut, _x.kec_x, _x.kec_y, _x.kec_sudut))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.centx, _x.centy, _x.sudut, _x.kec_x, _x.kec_y, _x.kec_sudut,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6h = None
def _get_struct_6h():
    global _struct_6h
    if _struct_6h is None:
        _struct_6h = struct.Struct("<6h")
    return _struct_6h
